services:
  web:
    image: nginx:latest # Using the default Nginx image with custom configuration.
    volumes:
      # Mount the application code for live updates
      - ./:/var/www
      # Mount the Nginx configuration file
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # Map port 80 inside the container to the port specified by 'NGINX_PORT' on the host machine
      - "80:80"
    depends_on:
      app:
        condition: service_started
    networks:
      - laravel

  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www
    depends_on:
      db:
        condition: service_started
      db_test:
        condition: service_started
    networks:
      - laravel

  db:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - laravel

  db_test:
    container_name: postgres-db-test
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data-test:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  db-data:
  db-data-test:


